// packages/svelte/src/lib/Auth/interfaces/EmailAuth.svelte
<script lang="ts">
	import type { SupabaseClient } from '@supabase/supabase-js';
	import Anchor from '$lib/UI/Anchor.svelte';
	import Button from '$lib/UI/Button.svelte';
	import Container from '$lib/UI/Container.svelte';
	import Input from '$lib/UI/Input.svelte';
	import Label from '$lib/UI/Label.svelte';
	import Message from '$lib/UI/Message.svelte';
	import { VIEWS, type I18nVariables, type ViewType } from '@supabase/auth-ui-shared';
	import type { Appearance } from '$lib/types';

	export let authView: ViewType = 'sign_in';
	export let email = '';
	export let password = '';
	export let supabaseClient: SupabaseClient;
	export let redirectTo: string | undefined = undefined;
	export let showLinks = false;
	export let magicLink = true;
	export let i18n: I18nVariables;
	export let appearance: Appearance;

	let message = '';
	let error = '';
	let loading = false;

	let lngKey: 'sign_in' | 'sign_up' = authView === 'sign_in' ? 'sign_in' : 'sign_up';

	async function handleSubmit() {
		loading = true;
		error = '';
		message = '';

		switch (authView) {
			case VIEWS.SIGN_IN:
				const { error: signInError } = await supabaseClient.auth.signInWithPassword({
					email,
					password
				});
				if (signInError) error = signInError.message;
				loading = false;
				break;
			case VIEWS.SIGN_UP:
				const {
					data: { user: signUpUser, session: signUpSession },
					error: signUpError
				} = await supabaseClient.auth.signUp({
					email,
					password,
					options: {
						emailRedirectTo: redirectTo
					}
				});

				if (signUpError) error = signUpError.message;
				// Check if session is null -> email confirmation setting is turned on
				else if (signUpUser && !signUpSession) message = i18n.sign_up?.confirmation_text as string;
				break;
		}
		loading = false;
	}
</script>

<form method="post" on:submit|preventDefault={handleSubmit}>
	<Container direction="vertical" gap="large" {appearance}>
		<Container direction="vertical" gap="large" {appearance}>
			<div>
				<Label for="email" {appearance}>{i18n?.[lngKey]?.email_label}</Label>
				<Input
					id="email"
					type="email"
					name="email"
					autofocus
					placeholder={i18n?.[lngKey]?.email_input_placeholder}
					bind:value={email}
					autocomplete="email"
					{appearance}
				/>
			</div>
			<div>
				<Label for="password" {appearance}>{i18n?.[lngKey]?.password_label}</Label>
				<Input
					id="password"
					type="password"
					name="password"
					placeholder={i18n?.[lngKey]?.password_input_placeholder}
					bind:value={password}
					autocomplete={authView === VIEWS.SIGN_IN ? 'current-password' : 'new-password'}
					{appearance}
				/>
			</div>
		</Container>
		<Button type="submit" color="primary" {appearance}>{i18n?.[lngKey]?.button_label}</Button>

		{#if showLinks}
			<Container direction="vertical" gap="small" {appearance}>
				{#if authView === VIEWS.SIGN_IN && magicLink}
					<Anchor
						on:click={(e) => {
							e.preventDefault();
							authView = VIEWS.MAGIC_LINK;
						}}
						href="#auth-magic-link"
						{appearance}
						>{i18n?.magic_link?.link_text}
					</Anchor>
				{/if}
				{#if authView === VIEWS.SIGN_IN}
					<Anchor
						on:click={(e) => {
							e.preventDefault();
							authView = VIEWS.FORGOTTEN_PASSWORD;
						}}
						href="#auth-forgot-password"
						{appearance}
					>
						{i18n?.forgotten_password?.link_text}</Anchor
					>
					<Anchor
						on:click={(e) => {
							e.preventDefault();
							authView = VIEWS.SIGN_UP;
						}}
						href="#auth-sign-up"
						{appearance}
					>
						{i18n?.sign_up?.link_text}
					</Anchor>
				{:else}
					<Anchor
						on:click={(e) => {
							e.preventDefault();
							authView = VIEWS.SIGN_IN;
						}}
						href="#auth-sign-in"
						{appearance}
					>
						{i18n?.sign_in?.link_text}
					</Anchor>
				{/if}
			</Container>
		{/if}
	</Container>

	{#if message}
		<Message {appearance}>
			{message}
		</Message>
	{/if}
	{#if error}
		<Message color="danger" {appearance}>
			{error}
		</Message>
	{/if}
</form>

<style>
	form {
		width: 100%;
	}
</style>

// packages/solid/src/components/Auth/interfaces/EmailAuth.tsx
/* eslint-disable no-case-declarations */
import { SupabaseClient } from '@supabase/supabase-js'
import { createEffect, createSignal, Setter } from 'solid-js'
import {
  I18nVariables,
  RedirectTo,
  ViewSignUp,
  ViewSignIn,
  ViewsMap,
  ViewType,
} from '@supabase/auth-ui-shared'
import { Appearance, FormEvent } from '../../../types'
import { Anchor, Button, Container, Input, Label, Message } from '../../UI'

export interface EmailAuthProps {
  authView: ViewSignIn | ViewSignUp
  defaultEmail: string
  defaultPassword: string
  setAuthView: Setter<ViewType>
  setDefaultEmail: (email: string) => void
  setDefaultPassword: (password: string) => void
  supabaseClient: SupabaseClient
  showLinks?: boolean
  redirectTo?: RedirectTo
  magicLink?: boolean
  i18n: I18nVariables
  appearance?: Appearance
}

const VIEWS: ViewsMap = {
  SIGN_IN: 'sign_in',
  SIGN_UP: 'sign_up',
  FORGOTTEN_PASSWORD: 'forgotten_password',
  MAGIC_LINK: 'magic_link',
  UPDATE_PASSWORD: 'update_password',
}

function EmailAuth(props: EmailAuthProps) {
  const [isMounted, setIsMounted] = createSignal<boolean>(true)
  const [email, setEmail] = createSignal(props.defaultEmail)
  const [password, setPassword] = createSignal(props.defaultPassword)
  const [error, setError] = createSignal('')
  const [loading, setLoading] = createSignal(false)
  const [message, setMessage] = createSignal('')

  createEffect(() => {
    setEmail(props.defaultEmail)
    setPassword(props.defaultPassword)

    return () => {
      setIsMounted(() => false)
    }
  })

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)
    switch (props.authView) {
      case 'sign_in':
        const { error: signInError } =
          await props.supabaseClient.auth.signInWithPassword({
            email: email(),
            password: password(),
          })
        if (signInError) setError(signInError.message)
        break
      case 'sign_up':
        const {
          data: { user: signUpUser, session: signUpSession },
          error: signUpError,
        } = await props.supabaseClient.auth.signUp({
          email: email(),
          password: password(),
          options: {
            emailRedirectTo: props.redirectTo,
          },
        })
        if (signUpError) setError(signUpError.message)
        // Check if session is null -> email confirmation setting is turned on
        else if (signUpUser && !signUpSession)
          setMessage(props.i18n.sign_up?.confirmation_text as string)
        break
    }

    /*
     * it is possible the auth component may have been unmounted at this point
     * check if component is mounted before setting a useState
     */
    if (isMounted()) setLoading(false)
  }

  const handleViewChange = (newView: ViewType) => {
    props.setDefaultEmail(email())
    props.setDefaultPassword(password())
    props.setAuthView(newView)
  }

  return (
    <form
      id={props.authView === 'sign_in' ? `auth-sign-in` : `auth-sign-up`}
      onSubmit={handleSubmit}
      autocomplete={'on'}
      style={{ width: '100%' }}
    >
      <Container direction="vertical" gap="large" appearance={props.appearance}>
        <Container
          direction="vertical"
          gap="large"
          appearance={props.appearance}
        >
          <div>
            <Label for="email" appearance={props.appearance}>
              {props.i18n?.[props.authView]?.email_label}
            </Label>
            <Input
              id="email"
              type="email"
              name="email"
              autofocus
              placeholder={
                props.i18n?.[props.authView]?.email_input_placeholder
              }
              value={email()}
              onkeyup={(e) => setEmail(() => e.currentTarget.value)}
              autocomplete="email"
              appearance={props.appearance}
            />
          </div>
          <div>
            <Label for="password" appearance={props.appearance}>
              {props.i18n?.[props.authView]?.password_label}
            </Label>
            <Input
              id="password"
              type="password"
              name="password"
              placeholder={
                props.i18n?.[props.authView]?.password_input_placeholder
              }
              value={password()}
              onkeyup={(e) => setPassword(() => e.currentTarget.value)}
              autocomplete={
                props.authView === 'sign_in'
                  ? 'current-password'
                  : 'new-password'
              }
              appearance={props.appearance}
            />
          </div>
        </Container>

        <Button
          type="submit"
          color="primary"
          loading={loading()}
          appearance={props.appearance}
        >
          {props.i18n?.[props.authView]?.button_label}
        </Button>

        {props.showLinks && (
          <Container
            direction="vertical"
            gap="small"
            appearance={props.appearance}
          >
            {props.authView === VIEWS.SIGN_IN && props.magicLink && (
              <Anchor
                href="#auth-magic-link"
                onClick={(e) => {
                  e.preventDefault()
                  props.setAuthView(VIEWS.MAGIC_LINK)
                }}
                appearance={props.appearance}
              >
                {props.i18n?.magic_link?.link_text}
              </Anchor>
            )}
            {props.authView === VIEWS.SIGN_IN && (
              <Anchor
                href="#auth-forgot-password"
                onClick={(e) => {
                  e.preventDefault()
                  props.setAuthView(VIEWS.FORGOTTEN_PASSWORD)
                }}
                appearance={props.appearance}
              >
                {props.i18n?.forgotten_password?.link_text}
              </Anchor>
            )}
            {props.authView === VIEWS.SIGN_IN ? (
              <Anchor
                href="#auth-sign-up"
                onClick={(e) => {
                  e.preventDefault()
                  handleViewChange(VIEWS.SIGN_UP)
                }}
                appearance={props.appearance}
              >
                {props.i18n?.sign_up?.link_text}
              </Anchor>
            ) : (
              <Anchor
                href="#auth-sign-in"
                onClick={(e) => {
                  e.preventDefault()
                  handleViewChange(VIEWS.SIGN_IN)
                }}
                appearance={props.appearance}
              >
                {props.i18n?.sign_in?.link_text}
              </Anchor>
            )}
          </Container>
        )}
      </Container>
      {message && <Message appearance={props.appearance}>{message()}</Message>}
      {error && (
        <Message color="danger" appearance={props.appearance}>
          {error()}
        </Message>
      )}
    </form>
  )
}

export { EmailAuth }
