// packages/svelte/src/lib/Auth/interfaces/UpdatePassword.svelte
<script lang="ts">
	import type { SupabaseClient } from '@supabase/supabase-js';
	import Anchor from '$lib/UI/Anchor.svelte';
	import Button from '$lib/UI/Button.svelte';
	import Container from '$lib/UI/Container.svelte';
	import Input from '$lib/UI/Input.svelte';
	import Label from '$lib/UI/Label.svelte';
	import Message from '$lib/UI/Message.svelte';
	import { VIEWS, type I18nVariables, type ViewType } from '@supabase/auth-ui-shared';
	import type { Appearance } from '$lib/types';

	export let i18n: I18nVariables;
	export let supabaseClient: SupabaseClient;
	export let authView: ViewType;
	export let appearance: Appearance;
	export let showLinks = false;

	let password = '';
	let message = '';
	let error = '';
	let loading = false;

	async function handleSubmit() {
		loading = true;
		error = '';
		message = '';
		const { data, error: resetPasswordError } = await supabaseClient.auth.updateUser({
			password
		});
		if (resetPasswordError) error = resetPasswordError.message;
		else message = i18n.update_password?.confirmation_text as string;
		loading = false;
	}
</script>

<form id="auth-update-password" method="post" on:submit|preventDefault={handleSubmit}>
	<Container direction="vertical" gap="large" {appearance}>
		<Container direction="vertical" gap="large" {appearance}>
			<div>
				<Label for="password" {appearance}>
					{i18n?.update_password?.password_label}
				</Label>
				<Input
					id="password"
					type="password"
					name="password"
					autofocus
					placeholder={i18n?.update_password?.password_label}
					bind:value={password}
					autocomplete="password"
					{appearance}
				/>
			</div>
			<Button type="submit" color="primary" {loading} {appearance}>
				{i18n?.update_password?.button_label}
			</Button>
		</Container>

		{#if showLinks}
			<Anchor
				on:click={(e) => {
					e.preventDefault();
					authView = VIEWS.SIGN_IN;
				}}
				href="#auth-magic-link"
				{appearance}>{i18n?.sign_in?.link_text}</Anchor
			>
		{/if}
		{#if message}
			<Message {appearance}>
				{message}
			</Message>
		{/if}
		{#if error}
			<Message color="danger" {appearance}>
				{error}
			</Message>
		{/if}
	</Container>
</form>

<style>
	form {
		width: 100%;
	}
</style>

// packages/solid/src/components/Auth/interfaces/UpdatePassword.tsx
import { SupabaseClient } from '@supabase/supabase-js'
import { createSignal, Show } from 'solid-js'
import { I18nVariables } from '@supabase/auth-ui-shared'
import { Appearance, FormEvent } from '../../../types'
import { Button, Container, Input, Label, Message } from '../../UI'

function UpdatePassword(props: {
  supabaseClient: SupabaseClient
  i18n: I18nVariables
  appearance?: Appearance
}) {
  const [password, setPassword] = createSignal('')
  const [error, setError] = createSignal('')
  const [message, setMessage] = createSignal('')
  const [loading, setLoading] = createSignal(false)

  const handlePasswordReset = async (e: FormEvent) => {
    e.preventDefault()
    setError('')
    setMessage('')
    setLoading(true)
    const { error } = await props.supabaseClient.auth.updateUser({
      password: password(),
    })
    if (error) setError(error.message)
    else setMessage(props.i18n.update_password?.confirmation_text as string)
    setLoading(false)
  }

  return (
    <form id="auth-update-password" onSubmit={handlePasswordReset}>
      <Container
        gap="large"
        direction={'vertical'}
        appearance={props.appearance}
      >
        <Container
          gap="large"
          direction="vertical"
          appearance={props.appearance}
        >
          <div>
            <Label for="password" appearance={props.appearance}>
              {props.i18n?.update_password?.password_label}
            </Label>
            <Input
              id="password"
              name="password"
              autofocus
              placeholder={props.i18n?.update_password?.password_label}
              type="password"
              onkeyup={(e) => setPassword(e.currentTarget.value)}
              appearance={props.appearance}
            />
          </div>
          <Button
            type="submit"
            color="primary"
            loading={loading()}
            appearance={props.appearance}
          >
            {props.i18n?.update_password?.button_label}
          </Button>
        </Container>

        <Show when={message()}>
          <Message appearance={props.appearance}>{message()}</Message>
        </Show>
        <Show when={error()}>
          <Message appearance={props.appearance}>{message()}</Message>
        </Show>
      </Container>
    </form>
  )
}

export { UpdatePassword }
