// packages/solid/src/components/UI/Anchor.tsx
import { css } from '@stitches/core'
import { generateClassNames } from '../../../common/theming'
import { Appearance } from '../../types'
import { JSX } from 'solid-js/jsx-runtime'
import { Component, JSXElement } from 'solid-js'

const anchorHTMLAttributes = css({
  fontFamily: '$bodyFontFamily',
  fontSize: '$baseBodySize',
  marginBottom: '$anchorBottomMargin',
  color: '$anchorTextColor',
  display: 'block',
  textAlign: 'center',
  textDecoration: 'underline',
  '&:hover': {
    color: '$anchorTextHoverColor',
  },
  fontWeight:'200',
  textDecorationLine:'none'
})

interface LabelProps extends JSX.AnchorHTMLAttributes<HTMLAnchorElement> {
  children:JSXElement 
  appearance?: Appearance
}

const Anchor: Component<LabelProps> = (props) => {
  const classNames = generateClassNames(
    'anchor',
    anchorHTMLAttributes(),
    props.appearance
  )

  return (
    <a
      {...props}
      style={props.appearance?.style?.anchor}
      class={classNames.join(' ')}
    >
      {props.children}
    </a>
  )
}

export { Anchor }

// packages/react/src/components/UI/Anchor.tsx
import { css } from '@stitches/core'
import { generateClassNames } from '../../../common/theming'
import { Appearance } from '../../types'

const anchorHTMLAttributes = css({
  fontFamily: '$bodyFontFamily',
  fontSize: '$baseBodySize',
  marginBottom: '$anchorBottomMargin',
  color: '$anchorTextColor',
  display: 'block',
  textAlign: 'center',
  textDecoration: 'underline',
  '&:hover': {
    color: '$anchorTextHoverColor',
  },
})

interface LabelProps extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
  children: React.ReactNode
  appearance?: Appearance
}

const Anchor: React.FC<LabelProps> = ({ children, appearance, ...props }) => {
  const classNames = generateClassNames(
    'anchor',
    anchorHTMLAttributes(),
    appearance
  )

  return (
    <a
      {...props}
      style={appearance?.style?.anchor}
      className={classNames.join(' ')}
    >
      {children}
    </a>
  )
}

export { Anchor }
