// packages/solid/src/components/UI/Label.tsx
import { css } from '@stitches/core'
import { Component, JSXElement, JSX } from 'solid-js'
import { generateClassNames } from '@supabase/auth-ui-shared'
import { Appearance } from '../../types'

const labelDefaultStyles = css({
  fontFamily: '$labelFontFamily',
  fontSize: '$baseLabelSize',
  marginBottom: '$labelBottomMargin',
  color: '$inputLabelText',
  display: 'block',
})

interface LabelProps extends JSX.LabelHTMLAttributes<HTMLLabelElement> {
  children: JSXElement
  appearance?: Appearance
}

const Label: Component<LabelProps> = (props) => {
  const classNames = generateClassNames(
    'label',
    labelDefaultStyles(),
    props.appearance
  )

  return (
    <label
      {...props}
      style={props.appearance?.style?.label}
      class={classNames.join(' ')}
    >
      {props.children}
    </label>
  )
}

export { Label }

// packages/react/src/components/UI/Label.tsx
import { css } from '@stitches/core'
import { generateClassNames } from '@supabase/auth-ui-shared'
import { Appearance } from '../../types'

const labelDefaultStyles = css({
  fontFamily: '$labelFontFamily',
  fontSize: '$baseLabelSize',
  marginBottom: '$labelBottomMargin',
  color: '$inputLabelText',
  display: 'block',
})

interface LabelProps extends React.LabelHTMLAttributes<HTMLLabelElement> {
  children: React.ReactNode
  appearance?: Appearance
}

const Label: React.FC<LabelProps> = ({ children, appearance, ...props }) => {
  const classNames = generateClassNames(
    'label',
    labelDefaultStyles(),
    appearance
  )

  return (
    <label
      {...props}
      style={appearance?.style?.label}
      className={classNames.join(' ')}
    >
      {children}
    </label>
  )
}

export { Label }
