// packages/solid/src/components/UI/Anchor.tsx
import { css } from '@stitches/core'
import { generateClassNames } from '@supabase/auth-ui-shared'
import { Appearance } from '../../types'
import { JSX } from 'solid-js/jsx-runtime'
import { Component, JSXElement } from 'solid-js'

const anchorHTMLAttributes = css({
  fontFamily: '$bodyFontFamily',
  fontSize: '$baseBodySize',
  marginBottom: '$anchorBottomMargin',
  color: '$anchorTextColor',
  display: 'block',
  textAlign: 'center',
  textDecoration: 'underline',
  '&:hover': {
    color: '$anchorTextHoverColor',
  },
  fontWeight: '200',
  textDecorationLine: 'none',
})

interface LabelProps extends JSX.AnchorHTMLAttributes<HTMLAnchorElement> {
  children: JSXElement
  appearance?: Appearance
}

const Anchor: Component<LabelProps> = (props) => {
  const classNames = generateClassNames(
    'anchor',
    anchorHTMLAttributes(),
    props.appearance
  )

  return (
    <a
      {...props}
      style={props.appearance?.style?.anchor}
      class={classNames.join(' ')}
    >
      {props.children}
    </a>
  )
}

export { Anchor }

// packages/svelte/src/lib/UI/Anchor.svelte
<script lang="ts">
	import type { Appearance } from '$lib/types';
	import { css } from '@stitches/core';
	import { generateClassNames } from '@supabase/auth-ui-shared';

	const anchorHTMLAttributes = css({
		fontFamily: '$bodyFontFamily',
		fontSize: '$baseBodySize',
		marginBottom: '$anchorBottomMargin',
		color: '$anchorTextColor',
		display: 'block',
		textAlign: 'center',
		textDecoration: 'underline',
		'&:hover': {
			color: '$anchorTextHoverColor'
		}
	});

	type AnchorProps = svelte.JSX.HTMLAttributes<HTMLAnchorElement>;

	type $$Props = Omit<AnchorProps, 'href'> & {
		href: string;
		appearance?: Appearance;
	};

	export let href: string;
	export let appearance: Appearance = {};

	$: classNames = generateClassNames('anchor', anchorHTMLAttributes(), appearance);
</script>

<a on:click {href} {...$$restProps} style={appearance?.style?.anchor} class={classNames.join(' ')}>
	<slot />
</a>
