// packages/svelte/src/lib/Auth/interfaces/SocialAuth.svelte
<script lang="ts">
	import type { SupabaseClient, Provider } from '@supabase/supabase-js';
	import { template, type I18nVariables, type SocialLayout } from '@supabase/auth-ui-shared';
	import type { Appearance } from '$lib/types';
	import Button from '$lib/UI/Button.svelte';
	import Container from '$lib/UI/Container.svelte';
	import Icons from '$lib/Auth/Icons.svelte';
	import Divider from '$lib/UI/Divider.svelte';

	export let supabaseClient: SupabaseClient;
	export let socialLayout: SocialLayout;
	export let redirectTo: string | undefined = undefined;
	export let onlyThirdPartyProviders: boolean;
	export let i18n: I18nVariables;
	export let providers: Provider[] = [];
	export let appearance: Appearance;

	let error = '';
	let loading = false;

	$: verticalSocialLayout = socialLayout === 'vertical' ? true : false;

	async function handleProviderSignIn(provider: Provider) {
		loading = true;
		error = '';
		const { error: providerSigninError } = await supabaseClient.auth.signInWithOAuth({
			provider,
			options: {
				redirectTo
			}
		});
		if (providerSigninError) error = providerSigninError.message;
		loading = false;
	}

	function capitalize(word: string) {
		return word[0].toUpperCase() + word.slice(1).toLowerCase();
	}

	let iconTitle = (provider: string) =>
		template(i18n['sign_in']?.social_provider_text as string, {
			provider: capitalize(provider)
		});
</script>

{#if providers.length}
	<Container direction="vertical" gap="large" {appearance}>
		<Container
			direction={verticalSocialLayout ? 'vertical' : 'horizontal'}
			gap={verticalSocialLayout ? 'small' : 'medium'}
			{appearance}
		>
			{#each providers as provider}
				<Button
					aria-label={iconTitle(provider)}
					on:click={() => handleProviderSignIn(provider)}
					type="submit"
					color="default"
					{loading}
					{appearance}
				>
					<Icons {provider} />
					{#if verticalSocialLayout}
						{iconTitle(provider)}
					{/if}
				</Button>
			{/each}
		</Container>
	</Container>
	{#if !onlyThirdPartyProviders}
		<Divider {appearance} />
	{/if}
{/if}

// packages/react/src/components/Auth/interfaces/SocialAuth.tsx
import { Provider, SupabaseClient } from '@supabase/supabase-js'
import { useState } from 'react'
import { I18nVariables, SocialLayout } from '@supabase/auth-ui-shared'
import { Appearance } from '../../../types'
import { Button, Container, Divider } from './../../UI'
import * as SocialIcons from './../Icons'

interface SocialAuthProps {
  supabaseClient: SupabaseClient
  socialLayout: SocialLayout
  providers?: Provider[]
  redirectTo: RedirectTo
  onlyThirdPartyProviders: boolean
  view: 'sign_in' | 'sign_up'
  i18n: I18nVariables
  appearance?: Appearance
}

type RedirectTo = undefined | string

function SocialAuth({
  supabaseClient,
  socialLayout = 'vertical',
  providers,
  redirectTo,
  onlyThirdPartyProviders,
  view,
  i18n,
  appearance,
}: SocialAuthProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const verticalSocialLayout = socialLayout === 'vertical' ? true : false

  const handleProviderSignIn = async (provider: Provider) => {
    setLoading(true)
    const { error } = await supabaseClient.auth.signInWithOAuth({
      provider,
      options: { redirectTo },
    })
    if (error) setError(error.message)
    setLoading(false)
  }

  function capitalize(word: string) {
    const lower = word.toLowerCase()
    return word.charAt(0).toUpperCase() + lower.slice(1)
  }

  return (
    <>
      {providers && providers.length > 0 && (
        <>
          <Container gap="large" direction="vertical" appearance={appearance}>
            <Container
              direction={verticalSocialLayout ? 'vertical' : 'horizontal'}
              gap={verticalSocialLayout ? 'small' : 'medium'}
              appearance={appearance}
            >
              {providers.map((provider: Provider) => {
                const AuthIcon = SocialIcons[provider]
                return (
                  <Button
                    key={provider}
                    color="default"
                    icon={AuthIcon ? <AuthIcon /> : ''}
                    loading={loading}
                    onClick={() => handleProviderSignIn(provider)}
                    appearance={appearance}
                  >
                    {verticalSocialLayout &&
                      i18n[view]?.social_provider_text +
                        ' ' +
                        capitalize(provider)}
                  </Button>
                )
              })}
            </Container>
          </Container>
          {!onlyThirdPartyProviders && <Divider appearance={appearance} />}
        </>
      )}
    </>
  )
}

export { SocialAuth }
